import React from 'react';
import {createRoot} from 'react-dom/client';
import {MemoryRouter, Routes, Route} from 'react-router-dom';
import {QueryClient, QueryClientProvider} from '@tanstack/react-query';
import {AuthContext} from './src/auth/authContextObject';
import {apiClient} from './src/lib/apiClient';
import {ThemeProvider} from './src/theme/ThemeProvider';
import {MainLayout} from './src/layouts/MainLayout';
import {StudentHomePage} from './src/pages/student-training/StudentHomePage';
import {DashboardPage} from './src/pages/coach-dashboard/DashboardPage';
import {WorkoutLogPage} from './src/pages/student-training/WorkoutLogPage';
import {ExerciseDetailPage} from './src/pages/exercises/ExerciseDetailPage';
import './src/index.css';
const role = new URLSearchParams(location.search).get('role') === 'coach' ? 'COACH' : 'STUDENT';
const mode = new URLSearchParams(location.search).get('view');
const user={id:'qa-student',name:'Atleta de prueba',email:'qa@example.test',role,isActive:true};
const exercise={id:'qa-exercise',name:'Sentadilla trasera',muscleGroup:'Piernas',instructions:'Mantén el control durante todo el movimiento.',videoUrl:'https://www.youtube.com/watch?v=dQw4w9WgXcQ',isActive:true};
const log={id:'qa-log',sessionId:'qa-session',durationMinutes:null,performedAt:new Date().toISOString(),completionStatus:'PARTIAL',setLogs:[],session:{name:'Fuerza — sesión A',week:{number:2,block:{name:'Base',program:{name:'Programa de fuerza'}}}}};
const summary={totalWorkouts:8,totalSetLogs:48,averageDurationMinutes:52,averageOverallRpe:7.4,averageFatigue:4,trainingFrequencyPerWeek:2.8,lastWorkoutAt:log.performedAt};
apiClient.get=async(path)=> {
 let data=[];
 if(path.startsWith('/workout-logs/evolution')) data={summary,recentPerformance:{averageOverallRpe:7.4,workoutsRegistered:9,lastActivityAt:log.performedAt,effortPoints:[{performedAt:'2026-10-01T12:00:00Z',overallRpe:7},{performedAt:'2026-10-03T12:00:00Z',overallRpe:8}]}};
 else if(path.startsWith('/workout-logs/qa-log')) data=log;
 else if(path.startsWith('/workout-logs')) data=[log];
 else if(path.startsWith('/student/sessions/')) data={exercises:[{id:'qa-prescription',order:1,exercise,targetSets:3,targetRepsMin:5,targetRepsMax:5}]};
 else if(path.startsWith('/exercises/')) data=exercise;
 else if(path.startsWith('/students')) data=[user];
 else if(path.startsWith('/dashboard/summary')) data={totalStudents:12,activeStudents:10,activeAssignments:10,workoutsRegistered:120,workoutsFinished:110,completionStatusBreakdown:{completed:100,partial:9,skipped:1},summary};
 else if(path.startsWith('/dashboard/recent-activity')) data=[{...log,student:user}];
 return {data,meta:{total:1,totalPages:1,page:1,limit:20},error:null};
};
const path=mode==='workout'?'/workout-logs/qa-log':mode==='exercise'?'/exercises/qa-exercise':'/';
createRoot(document.getElementById('root')).render(<QueryClientProvider client={new QueryClient()}><AuthContext.Provider value={{status:'authenticated',user,logout:async()=>{},login:async()=>{}}}><ThemeProvider><MemoryRouter initialEntries={[path]}><Routes><Route element={<MainLayout/>}><Route path="/" element={role==='COACH'?<DashboardPage/>:<StudentHomePage/>}/><Route path="/workout-logs/:id" element={<WorkoutLogPage/>}/><Route path="/exercises/:id" element={<ExerciseDetailPage/>}/></Route></Routes></MemoryRouter></ThemeProvider></AuthContext.Provider></QueryClientProvider>);
