// Reproducible benchmark using the existing P0 demo seed in a disposable schema.
const { spawn, spawnSync } = require('node:child_process');
const { randomUUID } = require('node:crypto');
const path = require('node:path');
const root = path.join(__dirname, '..');
const backend = path.join(root, 'backend');
require('../backend/node_modules/dotenv').config({ path: path.join(backend, '.env'), quiet: true });
const { PrismaClient } = require('../backend/node_modules/@prisma/client');
async function main() {
  if (process.env.NODE_ENV === 'production') throw new Error('Solo demo local');
  const url = new URL(process.env.DATABASE_URL);
  if (!['localhost', '127.0.0.1', '[::1]'].includes(url.hostname)) throw new Error('Solo PostgreSQL local');
  const schema = `p1_perf_${randomUUID().replaceAll('-', '')}`;
  if (!/^p1_perf_[a-f0-9]{32}$/.test(schema)) throw new Error('Esquema inválido');
  const admin = new PrismaClient();
  let server;
  let created = false;
  try {
    await admin.$executeRawUnsafe(`CREATE SCHEMA "${schema}"`);
    created = true;
    url.searchParams.set('schema', schema);
    const env = { ...process.env, DATABASE_URL: url.href, NODE_ENV: 'test', PORT: '3103',
      DEMO_SEED_CONFIRM: '1', DEMO_PASSWORD: `Demo-${randomUUID()}-1`, PERF_API_URL: 'http://localhost:3103/api/v1',
      PERF_DATASET: 'Seed P0 sin modificaciones, esquema temporal aislado (3 alumnos, 24 sesiones, 18 entrenamientos).',
    };
    for (const args of [
      [path.join(backend, 'node_modules/prisma/build/index.js'), 'migrate', 'deploy'],
      [path.join(backend, 'node_modules/ts-node/dist/bin.js'), 'prisma/seed.ts'],
    ]) {
      const result = spawnSync(process.execPath, args, { cwd: backend, env, stdio: 'pipe' });
      if (result.status !== 0) throw new Error('No se pudo preparar el esquema demo temporal. No se imprimen secretos.');
    }
    server = spawn(process.execPath, ['dist/main.js'], { cwd: backend, env, stdio: 'ignore', windowsHide: true });
    let ready = false;
    for (let n = 0; n < 60; n++) {
      if (server.exitCode !== null) throw new Error('La API temporal no pudo arrancar');
      try { if ((await fetch(`${env.PERF_API_URL}/health/ready`)).ok) { ready = true; break; } } catch { /* wait for startup */ }
      await new Promise((resolve) => setTimeout(resolve, 250));
    }
    if (!ready) throw new Error('API temporal no disponible');
    const measured = spawnSync(process.execPath, [path.join(__dirname, 'performance-baseline.cjs')], { cwd: root, env, stdio: 'inherit' });
    if (measured.status !== 0) throw new Error('Falló la medición');
  } finally {
    if (server && server.exitCode === null) {
      const closed = new Promise((resolve) => server.once('exit', resolve));
      server.kill(); await closed;
    }
    // Only the schema generated by this exact invocation can be removed.
    if (created) await admin.$executeRawUnsafe(`DROP SCHEMA "${schema}" CASCADE`);
    await admin.$disconnect();
  }
}
main().catch((error) => { console.error(error.message); process.exitCode = 1; });
